spring:
  datasource:
    url: jdbc:h2:mem:bookstore_prod,DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: missio
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
      format_sql: false
  h2:
    console:
      enable: false
logging:
  level:
    com:
      rafaelmissio: INFO